# 网站标题
title: Example site

# 网站描述
description: Site description

# 网站的logo
favicon: https://when.run/avator.jpeg

# 网站url
url: https://example.com

# github链接
# github: https://github.com/x1ah

# 页脚
footer: © AI工作室

template: webstack

# google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: false
    default: google


content:
  categories:
    - name: 常用推荐
      sites:
        - name: Dribbble
          description: 全球UI设计师作品分享平台。
          url: https://dribbble.com/
          icon: ./icos/ollama.svg

        - name: Behance
          description: Adobe旗下的设计师交流平台，来自世界各地的设计师在这里分享自己的作品。
          url: https://behance.net/
          icon: ./icos/ollama.svg
    - name: 界面灵感
      sites:
        - name: 咕噜素材
          description: 质量很高的设计素材网站（推荐）
          url: https://www.gulusucai.com/
          icon: ./icos/ollama.svg